# Prod HollaEx Kit Docker-Copmose
services:
  hollaex-kit-redis:
    image: redis:7.2.0-alpine
    restart: always
    depends_on:
      - hollaex-kit-db
    ports:
      - 6379:6379
    env_file:
      - hollaex-kit.env
    command: ["sh", "-c", "redis-server --requirepass $${REDIS_PASSWORD}"]

  hollaex-kit-db:
    image: postgres:14.9-alpine
    restart: always
    volumes:
      - ./hollaex_db_vol:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - hollaex-kit.env
    command: ["sh", "-c", "export POSTGRES_DB=$${DB_NAME} && export POSTGRES_USER=$${DB_USERNAME} && export POSTGRES_PASSWORD=$${DB_PASSWORD} && ln -sf /usr/local/bin/docker-entrypoint.sh ./docker-entrypoint.sh && ./docker-entrypoint.sh postgres"]

  hollaex-kit-server-api:
    #image: hollaex/hollaex-kit:2.11.4-cli-deprecation-46ea26c
    build:
      context: .
      dockerfile: tools/Dockerfile
    restart: always
    env_file:
      - hollaex-kit.env
    entrypoint:
      - node
    command:
      - app.js
    ports:
      - 10010:10010
    depends_on:
      - hollaex-kit-redis
      - hollaex-kit-db

  hollaex-kit-server-stream:
    #image: hollaex/hollaex-kit:2.11.4-cli-deprecation-46ea26c
    build:
      context: .
      dockerfile: tools/Dockerfile
    restart: always
    env_file:
      - hollaex-kit.env
    entrypoint:
      - node
    command:
      - ws/index.js
    ports:
      - 10080:10080
    depends_on:
      - hollaex-kit-server-api
      - hollaex-kit-redis
      - hollaex-kit-db

  hollaex-kit-server-plugins:
    #image: hollaex/hollaex-kit:2.11.4-cli-deprecation-46ea26c
    build:
      context: .
      dockerfile: tools/Dockerfile
    restart: always
    env_file:
      - hollaex-kit.env
    entrypoint:
      - node
    command:
      - plugins/index.js
    ports:
      - 10011:10011
    depends_on:
      - hollaex-kit-server-api
      - hollaex-kit-redis
      - hollaex-kit-db
