# Prod HollaEx Kit Docker-Copmose
version: '3'
name: "local"
services:
  hollaex-kit-prod-redis:
    image: redis:7.2.0-alpine
    restart: unless-stopped
    depends_on:
      - hollaex-kit-prod-db
    ports:
      - 6379:6379
    env_file:
      - hollaex-kit.env
    command: ["sh", "-c", "redis-server --requirepass $${REDIS_PASSWORD}"]
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 100M
        reservations:
          cpus: "0.1"
          memory: 100M
    networks:
      - hollaex-kit
  hollaex-kit-prod-db:
    image: postgres:14.9-alpine
    restart: unless-stopped
    volumes:
      - hollaex_db_vol:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - hollaex-kit.env
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 100M
        reservations:
          cpus: "0.1"
          memory: 100M
    command: ["sh", "-c", "export POSTGRES_DB=$${DB_NAME} && export POSTGRES_USER=$${DB_USERNAME} && export POSTGRES_PASSWORD=$${DB_PASSWORD} && ln -sf /usr/local/bin/docker-entrypoint.sh ./docker-entrypoint.sh && ./docker-entrypoint.sh postgres"]
    networks:
      - hollaex-kit
  hollaex-kit-server-api:
    image: hollaex/hollaex-kit:2.10.0-cli-deprecation-10abcf5
    build:
      context: .
      dockerfile: tools/Dockerfile
    restart: unless-stopped
    env_file:
      - hollaex-kit.env
    entrypoint:
      - node
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 1024M
        reservations:
          cpus: "0.05"
          memory: 512M
    command:
      - app.js
    ports:
      - 10010:10010
    networks:
      - hollaex-kit
    depends_on:
      - hollaex-kit-prod-redis
      - hollaex-kit-prod-db
  hollaex-kit-server-stream:
    image: hollaex/hollaex-kit:2.10.0-cli-deprecation-10abcf5
    build:
      context: .
      dockerfile: tools/Dockerfile
    restart: unless-stopped
    env_file:
      - hollaex-kit.env
    entrypoint:
      - node
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 512M
        reservations:
          cpus: "0.05"
          memory: 256M
    command:
      - ws/index.js
    ports:
      - 10080:10080
    networks:
      - hollaex-kit
    depends_on:
      - hollaex-kit-server-api
      - hollaex-kit-prod-redis
      - hollaex-kit-prod-db
  hollaex-kit-server-plugins:
    image: hollaex/hollaex-kit:2.10.0-cli-deprecation-10abcf5
    build:
      context: .
      dockerfile: tools/Dockerfile
    restart: unless-stopped
    env_file:
      - hollaex-kit.env
    entrypoint:
      - node
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 1200M
        reservations:
          cpus: "0.05"
          memory: 700M
    command:
      - plugins/index.js
      - 10011:10011
    networks:
      - hollaex-kit
    depends_on:
      - hollaex-kit-server-api
      - hollaex-kit-prod-redis
      - hollaex-kit-prod-db
networks:
  hollaex-kit:
volumes:
  hollaex_db_vol:
