version: '3'
services:
  hollaex-web:
    image: hollaex-web
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: 128M
        reservations:
          cpus: "0.05"
          memory: 128M
    ports: 
      - 8080:80 
    networks:
      - local_hollaex-kit

networks:
  local_hollaex-kit:
    external: true

